### ISSUE TITLE
paho missing 1 required positional argument: 'callback_api_version'

### ISSUE THREAD

**Issue by sshort1955** [eschava/psmqtt#36]
Came across this after fresh install of psmqtt. Requirements.txt installs paho-mqtt V2.0, which has a breaking change with psmqtt. Fix for now that I found was to revert paho-mqtt to V1.6 by running this command:

sudo pip3 install "paho-mqtt < 2.0.0"

sudo is required because the psmqtt service runs under root.

**Comment by mbuette** [comment]
Came across the same issue yesterday. You'll need to modify the following line in src/task.py:
self.mqttc = paho.Client(**paho.CallbackAPIVersion.VERSION1,** client_id, clean_session=clean_session, userdata=self, protocol=paho.MQTTv311)
I'll try to create a PR for that, but I'm a noob at GitHub. Otherwise, thanks for your work!

**Comment by eschava** [comment]
seems to be fixed already
